# Generated by Django 6.0.6 on 2026-06-17 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField()),
                ('total_distance_miles', models.FloatField(default=0)),
                ('total_duration_hours', models.FloatField(default=0)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('route_geometry', models.JSONField(default=dict)),
                ('stops', models.JSONField(default=list)),
                ('events', models.JSONField(default=list)),
                ('daily_logs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
